#!/bin/bash

# Copyright (C) 2014 The SaberMod Project
# This file is free software; The SaberMod Project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

panic ()
{
    echo "ERROR: $@"
    exit 1
}

if [ $SET_TARGET_BUILD = "CLOOG" ];
then

panic "*******************************ﾓ∆ⅰﾚㄩЯ∑*******************************
                                                                             
       Sorry your build failed because                                       
       cloog failed to build the required                                    
       libraries.  Read:                                               
       https://gitlab.com/SaberMod/sabermod-manifest/blob/master/README.md   
       for system requirements and instructions.                             
                                                                             
       *******************************ﾓ∆ⅰﾚㄩЯ∑*******************************";
fi;

if [ $SET_TARGET_BUILD = "GCC" ];
then

panic "*******************************ﾓ∆ⅰﾚㄩЯ∑*******************************
                                                                             
       GCC has failed to build                                               
       Read:                                                           
       https://gitlab.com/SaberMod/sabermod-manifest/blob/master/README.md   
       for system requirements and instructions.                             
                                                                             
       *******************************ﾓ∆ⅰﾚㄩЯ∑*******************************";
fi;

