#!/bin/bash

# Copyright (C) 2014-2015 The SaberMod Project
# This file is free software; The SaberMod Project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

panic ()
{
    echo "ERROR: $@";
}

if [ -n $CLOOG_INSTALLED ];
then
    if [ $CLOOG_INSTALLED = "no" ];
    then
        echo "";
        echo "";
        echo "";
        panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************
                                                                                          
               Sorry your build failed because                                            
               host CLOOG libraries failed to install                                       
                                                                                          
               Email log to:                                                              
               sabermod.team@gmail.com                                                    
               for assistance.                                                            
                                                                                          
               Log is located at:                                                         
               $MAKE_LOG                                                                  
                                                                                          
           **********************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
        echo "";
        echo "";
        echo "";
    fi;
fi;

if [ -n $ISL_INSTALLED ];
then
    if [ $ISL_INSTALLED = "no" ];
    then
        echo "";
        echo "";
        echo "";
        panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************
                                                                                          
               Sorry your build failed because                                            
               host ISL libraries failed to install                                       
                                                                                          
               Email log to:                                                              
               sabermod.team@gmail.com                                                    
               for assistance.                                                            
                                                                                          
               Log is located at:                                                         
               $MAKE_LOG                                                                  
                                                                                          
           **********************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
        echo "";
        echo "";
        echo "";
    fi;
fi;

if [ $MPFR_INSTALLED = "no" ];
then
    echo "";
    echo "";
    echo "";
    panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************
                                                                                      
           Sorry your build failed because                                            
           host MPFR libraries failed to install                                       
                                                                                      
           Email log to:                                                              
           sabermod.team@gmail.com                                                    
           for assistance.                                                            
                                                                                      
           Log is located at:                                                         
           $MAKE_LOG                                                                  
                                                                                      
       **********************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";
fi;

if [ $GMP_INSTALLED = "no" ];
then
    echo "";
    echo "";
    echo "";
    panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************
                                                                                      
           Sorry your build failed because                                            
           host GMP libraries failed to install                                       
                                                                                      
           Email log to:                                                              
           sabermod.team@gmail.com                                                    
           for assistance.                                                            
                                                                                      
           Log is located at:                                                         
           $MAKE_LOG                                                                  
                                                                                      
       **********************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";
fi;

if [ $SET_TARGET_BUILD = "GCC" ];
then
    echo "";
    echo "";
    echo "";
    panic "**********************************ﾓ∆ⅰﾚㄩЯ∑**********************************
                                                                                      
           GCC has failed to build                                                    
           Read:                                                                      
           https://gitlab.com/SaberMod/sabermod-manifest/blob/master/README.md        
           for system requirements and instructions.                                  
                                                                                      
           Email log to:                                                              
           sabermod.team@gmail.com                                                    
           for assistance.                                                            
                                                                                      
           Log is located at:                                                         
           $MAKE_LOG                                                                  
                                                                                      
       **********************************ﾓ∆ⅰﾚㄩЯ∑**********************************";
    echo "";
    echo "";
    echo "";
fi;

unset CLOOG_INSTALLED;
unset ISL_INSTALLED;
unset MPFR_INSTALLED;
unset GMP_INSTALLED;
unset SET_TARGET_BUILD;
