#!/bin/bash

# Copyright (C) 2015 The SaberMod Project
# This file is free software; The SaberMod Project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

success ()
{
    echo "SUCCESS: $@"
}

if [ $SET_TARGET_BUILD = "HOST" ];
then
    echo "";
    echo "";
    echo "";
    success "*****************ㄅㄩςς∑ㄅㄅ*****************
                                                         
             HOST libraries have successfully built                
                                                         
         *****************ㄅㄩςς∑ㄅㄅ*****************";
    echo "";
    echo "";
    echo "";
fi;

if [ $SET_TARGET_BUILD = "GCC" ];
then
    echo "";
    echo "";
    echo "";
    success "*****************ㄅㄩςς∑ㄅㄅ*****************
                                                         
             GCC has successfully built                  
             The toolchain is located at:                
             $TOOLCHAIN_PREFIX_PATH                      
                                                         
         *****************ㄅㄩςς∑ㄅㄅ*****************";
    echo "";
    echo "";
    echo "";
fi;
